Java/spock
nspectator/katas pull request #52
Opened 2016-12-14 06:30 UTC by GeloRuse

Решение и тест для задач Equi (точки равновесия), Labyrinth (путь в лабиринте), MineFields (минное поле с подсказками), Yahtzee (вычисление счёта по категории).
Тонков Руслан, ПИН-1406.

2016-12-14 11:35 UTC, jonny-novikov commented
@GeloRuse Which are the common reasons for upgrading gradle?
Branch has conflicts.

2016-12-14 11:46 UTC, GeloRuse commented
@jonny-novikov The working project had updated gradle with newer version of spock core (from 1.0 to 1.1). The changes in gradle files can be removed if irrelevant.

2016-12-14 13:03 UTC, rgordeev requested changes
есть замечания. поправь

2016-12-14 13:03 UTC, rgordeev commented on katas.iml
> +<?xml version="1.0" encoding="UTF-8"?>
нужно убрать специфичны файлы для IDE

2016-12-14 13:03 UTC, rgordeev commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
README  тоже редактировать не стоит

2016-12-14 13:03 UTC, rgordeev commented on src/main/java/org/nspectator/katas/utils/StreamUtils.java
> -package org.nspectator.katas.utils;
зачем удалил?

2016-12-14 13:06 UTC, GeloRuse commented on src/main/java/org/nspectator/katas/utils/StreamUtils.java
> -package org.nspectator.katas.utils;
Я решил что ваши файлы пойдут в мой пулл реквест и удалил все файлы, которые я не делал. Это ошибка, удалять файлы не надо.

2016-12-14 13:18 UTC, GeloRuse commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
@rgordeev Не пойму как исправить, строчка находится там, где должна быть. Никаких пробелов не пропущено.
Это изменение можно проигнорировать?

2016-12-14 17:24 UTC, GeloRuse commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
@rgordeev Все остальные проблемы устранены.

2016-12-15 08:20 UTC, GeloRuse commented
@rgordeev Делал перекачку файла README.md, копировал с оригинала, полностью удалял и создавал по новой - ничего не помогло. Я не пойму в чем проблема. Файлы идентичны, но  показывает, что есть разница. Можно не учитывать этот файл?

2016-12-16 08:36 UTC, rgordeev reviewed
зачтено

2016-12-16 08:36 UTC, rgordeev commented on src/main/java/org/nspectator/katas/yahtzee/Yahtzee.java
> +public class Yahtzee {
задача решена неверно, мы уже обсуждали ее решение на паре. нужно в конечном счете уметь считать результат, исользуя стратегию выбора на каждом шаге

2016-12-16 08:36 UTC, rgordeev commented on src/main/java/org/nspectator/katas/utils/StreamUtils.java
> -package org.nspectator.katas.utils;
как они, интересно, могли бы попсть в твой пулреквест, если ты их не менял? вот теперь онив реквест попали

2016-12-16 08:36 UTC, rgordeev commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
просто теперь там другой символ перевода строки

2016-12-16 08:36 UTC, rgordeev commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
оставь как есть, не мучайся

2016-12-16 08:36 UTC, rgordeev commented on list/Yehtzee/README.md
> +		4,4,4,4,4 scores 0
ок, я посмотрю

2016-12-16 08:36 UTC, rgordeev approved these changes

2016-12-16 08:36 UTC, merged