Java/spock
nspectator/katas pull request #53
Opened 2016-12-16 19:21 UTC by nkondrina

Решены задачи: BinaryGap, Equi, Labyrinth, LCD Digits.
Кондрина Наталья ПИН-1406.

2016-12-19 16:52 UTC, rgordeev requested changes

2016-12-19 16:52 UTC, rgordeev commented on src/main/java/org/nspectator/katas/labyrinth/Labyrinth.java
> +   /* private Boolean Searchputh(List<Point> puth1)
неиспользуемый код лучше удалить

2016-12-21 09:24 UTC, jonny-novikov commented
@nkondrina Please, look at the @rgordeev request for changes and complete

2017-02-26 19:46 UTC, jonny-novikov commented
3 month and I suppose PR is not relevant. Closing request as outdated.

2017-02-26 19:46 UTC, closed without merging